//
//  DateSelectionViewController.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DateSelectionViewController: UITableViewController, Dismissable {
  weak var dismissalDelegate: DismissalDelegate?
  var initialSelection: RangeOption = .currentDay

  // MARK: Object lifecycle
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }

  // MARK: View lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
  }

  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    updateSelection()
  }

  // MARK: UITableView specific functions
  func updateSelection() {
    log.verbose("")
    if let cell = tableView.cellForRow(at: IndexPath.init(row: initialSelection.rawValue, section: 0)),
      let cellText = cell.textLabel?.text {
      cell.textLabel?.text = "✔ " + cellText
    }
  }

  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    log.debug(indexPath)
    let option = RangeOption(rawValue: indexPath.row) ?? .currentDay
    dismissalDelegate?.finishedShowing(viewController: self, result: ["SelectedRange": option])
  }
}
