//
//  LoginRouter.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
  func toExaminer(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?

  // MARK: Routing
  func toExaminer(segue: UIStoryboardSegue?) {
    //We have no data here to pass over to Examiner view.
    //Authentication Token is stored directly to request adapter in sessionManager.
  }
}
