//
//  LoginModels.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  // MARK: Use cases
  enum Auth {
    struct Request {
      var bank: ESBank
    }
    struct Response {
      var error: ESError?
    }
    struct ViewModel {
      var errorMessage: String?
    }
  }
}
