//
//  LoginPresenter.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentLoginResponse(response: Login.Auth.Response)
}

class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?

  // MARK: Presentation
  func presentLoginResponse(response: Login.Auth.Response) {
    log.verbose("")
    let viewModel = Login.Auth.ViewModel(errorMessage: response.error?.message())
    viewController?.displayLoginResult(viewModel: viewModel)
  }
}
