//
//  LoginModels.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginResult {
  case success
  case failed(ESError)
  case pending
  case canceled
}

enum AuthenticationMode: String {
  case noAuth
  case skipUI = "AuthenticationSkipUI"
  case skipAccessControl = "AuthorizationSkipAccessControl"
  case withUI = "AuthenticationWithUI"
}

enum Login {
  // MARK: Use cases
  enum Auth {
    struct Request {
      var bank: ESBank
      var mode: AuthenticationMode
      var code: String?
    }

    struct Response {
      var result: LoginResult
    }

    struct ViewModel {
      var result: LoginResult
    }
  }
}
