//
//  OPLoginWorkerWorker.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OPLoginWorker: LoginWorker {
  func authenticate(_ completion: @escaping (ESError?) -> Void) {
    // OP Open API does not have a real authentication interface, so we just
    // set up route specifics and complete the operation

    sessionManager.adapter = OPRequestAdapter()
    RESTRoutes.accountAPIVersion = "v1"
    RESTRoutes.urlRoot = "https://sandbox.apis.op-palvelut.fi/"
    completion(nil)
  }
}
