//
//  TransactionModels.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct RowData {
  var title: String
  var value: String?
}

enum TransactionDetails {
  // MARK: Use cases
  enum Fetch {
    struct Request {
    }

    struct Response {
      var txn: ESTransaction
    }

    struct ViewModel {
      var amount: String
      var type: ESTransactionType
      var valuePairs: [RowData]
    }
  }
}
