//
//  TransactionInteractor.swift
//  ExamineSpending
//
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionBusinessLogic {
  func fetchDetails()
}

protocol TransactionDataStore {
  var currentTxn: ESTransaction? { get set }
}

class TransactionInteractor: TransactionBusinessLogic, TransactionDataStore {
  var presenter: TransactionPresentationLogic?
  var currentTxn: ESTransaction?

  func fetchDetails() {
    log.verbose("")
    let response = TransactionDetails.Fetch.Response(txn: currentTxn!)
    presenter?.presentDetails(response: response)
  }
}
